mac: Return trash items that are created by delete
Byron/trash-rs pull request #128
Opened 2024-12-04 18:16 UTC by eugenesvk

Builds upon the previous Linux PR for easier rebasing, will add comment to the existing PR not to split the discussion

https://github.com/Byron/trash-rs/pull/109

- add macos functions that return trashed items: **optionally** if called via `_with_info` functions (for both Finder with AppleScript and FS API), so there is no mandatory overhead for long lists
  - ✗ couldn't find a way to get OS trash timestamp even though it exists (Finders knows it, but the metadata field is returned empty for us, maybe this is also hidden in DSStore???), so using the same logic of calculating our own timestamps like for Linux
- added a few tests for both trash types (though only checking return item's name/parent as time/path@trash can be inconsistent, so no guaranteed way for us to compare them)
- added **stub** `with_info` function arguments for Linux/Win, but the actual logic is **not implemented**

- added the new configurable faster/better method of launching AppleScript via direct Objc bindings to the automation kit, think it should be the **new default**, but for now left the old method (via separate proc) as the default.
  - Although stdout is eating quotation marks separating paths, so had to manually insert ` /// ` as list separators:
    -  ?: can there be a "natural" path that contains ` /// `, meaning this is a buggy separator?

2024-12-08 09:51 UTC, Byron requested changes
Thanks for all your hard work on this.

Unfortunately `master` now is incompatible with this branch so it would need another round of rebasing and conflict resolution.

Regarding `osakit`, since it's also not really working, let's remove it right away and keep this PR focussed on returning the deleted items.

Thanks again.

2024-12-08 17:59 UTC, eugenesvk commented
Rebased.
And it's too early to kill osakit :), it turns out the issue is in cargo's test harness: macos applescript thingies must be run on the main thread, and tests don't allow that (see https://github.com/mdevils/rust-osakit/issues/2)
So the stalling issue won't appear for the main trash app, will update the docs then, but leave the cli method just in case someone would need to run trashing on a different thread

Do you know how to force tests to use the main thread?

2024-12-09 07:06 UTC, Byron reviewed
Thanks a lot for setting this up!

And that's fair enough, let's keep `osakit` as it may be useful to some.

> Do you know how to force tests to use the main thread?

First of all, I think you should be able to check if the current thread is the main thread.

```Rust
use std::thread;

fn main() {
    println!("Is this the main thread? {:?}", thread::current().name());
}
```

```
Is this the main thread? Some("main")
```

Then the test can bail if it's not main, but be enabled by default.
It is possible to restrict the amount of threads to run the tests to 1, but I don't know if that will be the main thread.

2024-12-09 07:08 UTC, eugenesvk commented
> It is possible to restrict the amount of threads to run the tests to 1, but I don't know if that will be the main thread.

no it unfortunately won't due to a regression in Rust, but it seems the alternative testing crate could add support for this https://github.com/nextest-rs/nextest/discussions/1959

2024-12-09 07:46 UTC, eugenesvk commented on src/macos/mod.rs
> +    Cli,
This seems to break the const fn , `default()` not allowed there?

2024-12-09 07:56 UTC, Byron commented on src/macos/mod.rs
> +    Cli,
True, `const` isn't supported with `Default` yet. Then that wouldn't work.

2024-12-09 15:09 UTC, eugenesvk commented on src/macos/mod.rs
> +    Cli,
reverted back

2024-12-24 07:59 UTC, joshuamegnauth54 commented
I wrote a unit test for #109 on the Freedesktop side, so you may be able to make use of that too. I didn't notice this PR until after I wrote it, but it shouldn't conflict with your work (I think).

* jackpot51/trash-rs#1

2026-09-13 16:30 UTC, Byron commented
Closed as too old and inactive.

2026-09-13 16:30 UTC, closed without merging