draft: Check trash path
Byron/trash-rs pull request #88
Opened 2023-10-17 19:07 UTC by EvysGarden

## Issue
The current implementation allows the removal of a trash folder with trash-rs

## Fix
This seems rather weird so i added a check for it.

## Note
I also added an example that simply passes all args to delete_all. I made it anyway so might as well push it.

This is marked as a draft because I'm not sure whether my code meets your quality.

2023-10-18 05:58 UTC, Byron requested changes
Thanks a lot for contributing, having such a check seems very reasonable.

Why would MacOS not have the example? The commit message didn't tell.

Further it seems that this is only implemented for FreeDesktop, and think this should be implement for all platforms. Once a test is available, CI can be used to validate the implementation as it's fine to try to delete the trash folder on CI for sure.

2023-10-18 07:03 UTC, EvysGarden commented
i added freedesktop support because i'm on a linux device and don't have a macos environment to test in.

I'll look into it but i can't properly test it.

2023-10-18 07:19 UTC, Byron commented
> I'll look into it but i can't properly test it.

Once there is an integration test that tries to delete the trash directory, CI will test it for you. And for this feature to go forward, this will be needed. Thanks for your understanding.

2024-01-31 19:47 UTC, arthurbacci commented on src/freedesktop.rs
> +                }
Should no action be performed in this case?

2025-04-23 17:01 UTC, closed without merging