Enhanced error reporting
Byron/trash-rs pull request #98
Opened 2024-02-04 19:53 UTC by bicarlsen

Addresses #96.

Adds an `Error::Os` variant so clients can more easily handle errors.
On Windows, maps errors immediately if a file is not found or not accessible.

2024-02-04 19:54 UTC, bicarlsen commented
Here's a first go at an update.

2024-02-05 06:24 UTC, Byron requested changes
Thanks a lot for your help!

Just one small issue to address and the PR can be merged.

2024-02-05 06:24 UTC, Byron commented on src/windows.rs
> +        log::trace!("Starting traverse_paths_recursively");
Could you remove all added logging? I think it's out of scope for this PR.

2024-02-05 08:16 UTC, merged

2024-02-05 08:16 UTC, Byron commented
Thanks a lot!